---
- name: thoughtworks go repository
  copy: src=thoughtworks-go-download.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: Install Java 1.7 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - which
   - java-1.7.0-openjdk

