---
- name: thoughtworks go repository
  copy: src=thoughtworks-go-download.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: Install Java 1.7 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - which
   - git
   - java-1.7.0-openjdk

- name: install go-server 
  yum: pkg=go-server-{{ go_version}} state=latest
  # notify:
  # - restart go-server

- name: install go-agent 
  yum: pkg=go-agent-{{ go_version}} state=latest
  # notify:
  # - restart go-agent

- name: start go-server
  service: name=go-server state=started

- name: start go-agent
  service: name=go-agent state=started